  name: Fetch SunBiz Data

  on:
    schedule:
      - cron: '0 10 * * 1'  # Every Monday at 10 AM UTC
    workflow_dispatch:      # Manual trigger
    push:
      branches: [main]      # Run on pushes to main

  jobs:
    fetch-data:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create data directory
        run: mkdir -p data

      - name: Fetch SunBiz data
        run: python fetch_sunbiz.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update SunBiz data - $(date +'%Y-%m-%d %H:%M')"
            git push
          fi

  Important notes:
  1. Copy this exactly as shown
  2. Use only spaces, no tabs
  3. Make sure the indentation is preserved
  4. The | character after run: allows multi-line commands

  To use this:
  1. Go to: https://github.com/BwagesTheFirst/Sunbiz-data-fetcher/blob/main/.github/workflows/fetch-sunbiz.yml
  2. Click the pencil icon to edit
  3. Select all (Ctrl+A) and delete
  4. Paste this complete version
  5. Click "Commit changes"

  This should fix the YAML syntax error!

> Annotations
  1 error
  Invalid workflow file: .github/workflows/fetch-sunbiz.yml#L46
  You have an error in your yaml syntax on line 46

● Let me count the lines to see what's on line 46. I think the issue might be with quotes or special characters.
  Here's a simplified version that should definitely work:

  Simplified Working Version:

  name: Fetch SunBiz Data

  on:
    workflow_dispatch:
    push:
      branches:
        - main

  jobs:
    fetch-data:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install packages
        run: pip install requests

      - name: Create directory
        run: mkdir -p data

      - name: Run script
        run: python fetch_sunbiz.py

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit changes
        run: |
          git add .
          git diff --staged --quiet || git commit -m "Update data"
          git push || echo "No changes to push"
